/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.axual.client.example.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Identification of am ApplicationLogEvent system */
@org.apache.avro.specific.AvroGenerated
public class ApplicationLogAlertKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3939393662154699876L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationLogAlertKey\",\"namespace\":\"io.axual.client.example.schema\",\"doc\":\"Identification of am ApplicationLogEvent system\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"The name of the application generating the LogEvent\"},{\"name\":\"address\",\"type\":\"string\",\"doc\":\"The address to send the alert to\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ApplicationLogAlertKey> ENCODER =
      new BinaryMessageEncoder<ApplicationLogAlertKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ApplicationLogAlertKey> DECODER =
      new BinaryMessageDecoder<ApplicationLogAlertKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ApplicationLogAlertKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ApplicationLogAlertKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ApplicationLogAlertKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ApplicationLogAlertKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ApplicationLogAlertKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ApplicationLogAlertKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ApplicationLogAlertKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ApplicationLogAlertKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The name of the application generating the LogEvent */
   private java.lang.CharSequence name;
  /** The address to send the alert to */
   private java.lang.CharSequence address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicationLogAlertKey() {}

  /**
   * All-args constructor.
   * @param name The name of the application generating the LogEvent
   * @param address The address to send the alert to
   */
  public ApplicationLogAlertKey(java.lang.CharSequence name, java.lang.CharSequence address) {
    this.name = name;
    this.address = address;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return address;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: address = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The name of the application generating the LogEvent
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * The name of the application generating the LogEvent
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The address to send the alert to
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * The address to send the alert to
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Creates a new ApplicationLogAlertKey RecordBuilder.
   * @return A new ApplicationLogAlertKey RecordBuilder
   */
  public static io.axual.client.example.schema.ApplicationLogAlertKey.Builder newBuilder() {
    return new io.axual.client.example.schema.ApplicationLogAlertKey.Builder();
  }

  /**
   * Creates a new ApplicationLogAlertKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicationLogAlertKey RecordBuilder
   */
  public static io.axual.client.example.schema.ApplicationLogAlertKey.Builder newBuilder(io.axual.client.example.schema.ApplicationLogAlertKey.Builder other) {
    if (other == null) {
      return new io.axual.client.example.schema.ApplicationLogAlertKey.Builder();
    } else {
      return new io.axual.client.example.schema.ApplicationLogAlertKey.Builder(other);
    }
  }

  /**
   * Creates a new ApplicationLogAlertKey RecordBuilder by copying an existing ApplicationLogAlertKey instance.
   * @param other The existing instance to copy.
   * @return A new ApplicationLogAlertKey RecordBuilder
   */
  public static io.axual.client.example.schema.ApplicationLogAlertKey.Builder newBuilder(io.axual.client.example.schema.ApplicationLogAlertKey other) {
    if (other == null) {
      return new io.axual.client.example.schema.ApplicationLogAlertKey.Builder();
    } else {
      return new io.axual.client.example.schema.ApplicationLogAlertKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for ApplicationLogAlertKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationLogAlertKey>
    implements org.apache.avro.data.RecordBuilder<ApplicationLogAlertKey> {

    /** The name of the application generating the LogEvent */
    private java.lang.CharSequence name;
    /** The address to send the alert to */
    private java.lang.CharSequence address;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.axual.client.example.schema.ApplicationLogAlertKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.address)) {
        this.address = data().deepCopy(fields()[1].schema(), other.address);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicationLogAlertKey instance
     * @param other The existing instance to copy.
     */
    private Builder(io.axual.client.example.schema.ApplicationLogAlertKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.address)) {
        this.address = data().deepCopy(fields()[1].schema(), other.address);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * The name of the application generating the LogEvent
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * The name of the application generating the LogEvent
      * @param value The value of 'name'.
      * @return This builder.
      */
    public io.axual.client.example.schema.ApplicationLogAlertKey.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * The name of the application generating the LogEvent
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * The name of the application generating the LogEvent
      * @return This builder.
      */
    public io.axual.client.example.schema.ApplicationLogAlertKey.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * The address to send the alert to
      * @return The value.
      */
    public java.lang.CharSequence getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * The address to send the alert to
      * @param value The value of 'address'.
      * @return This builder.
      */
    public io.axual.client.example.schema.ApplicationLogAlertKey.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.address = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * The address to send the alert to
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'address' field.
      * The address to send the alert to
      * @return This builder.
      */
    public io.axual.client.example.schema.ApplicationLogAlertKey.Builder clearAddress() {
      address = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ApplicationLogAlertKey build() {
      try {
        ApplicationLogAlertKey record = new ApplicationLogAlertKey();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.address = fieldSetFlags()[1] ? this.address : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ApplicationLogAlertKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<ApplicationLogAlertKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ApplicationLogAlertKey>
    READER$ = (org.apache.avro.io.DatumReader<ApplicationLogAlertKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.address);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.address = in.readString(this.address instanceof Utf8 ? (Utf8)this.address : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.address = in.readString(this.address instanceof Utf8 ? (Utf8)this.address : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










