/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.axual.client.example.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Object type that is supposed to be filled with a Random value. This should be used when the Key is irrelevant. */
@org.apache.avro.specific.AvroGenerated
public class Random extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3438181993295630952L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Random\",\"namespace\":\"io.axual.client.example.schema\",\"doc\":\"Object type that is supposed to be filled with a Random value. This should be used when the Key is irrelevant.\",\"fields\":[{\"name\":\"random\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The random value.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Random> ENCODER =
      new BinaryMessageEncoder<Random>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Random> DECODER =
      new BinaryMessageDecoder<Random>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Random> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Random> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Random> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Random>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Random to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Random from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Random instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Random fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The random value. */
   private java.lang.CharSequence random;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Random() {}

  /**
   * All-args constructor.
   * @param random The random value.
   */
  public Random(java.lang.CharSequence random) {
    this.random = random;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return random;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: random = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'random' field.
   * @return The random value.
   */
  public java.lang.CharSequence getRandom() {
    return random;
  }


  /**
   * Sets the value of the 'random' field.
   * The random value.
   * @param value the value to set.
   */
  public void setRandom(java.lang.CharSequence value) {
    this.random = value;
  }

  /**
   * Creates a new Random RecordBuilder.
   * @return A new Random RecordBuilder
   */
  public static io.axual.client.example.schema.Random.Builder newBuilder() {
    return new io.axual.client.example.schema.Random.Builder();
  }

  /**
   * Creates a new Random RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Random RecordBuilder
   */
  public static io.axual.client.example.schema.Random.Builder newBuilder(io.axual.client.example.schema.Random.Builder other) {
    if (other == null) {
      return new io.axual.client.example.schema.Random.Builder();
    } else {
      return new io.axual.client.example.schema.Random.Builder(other);
    }
  }

  /**
   * Creates a new Random RecordBuilder by copying an existing Random instance.
   * @param other The existing instance to copy.
   * @return A new Random RecordBuilder
   */
  public static io.axual.client.example.schema.Random.Builder newBuilder(io.axual.client.example.schema.Random other) {
    if (other == null) {
      return new io.axual.client.example.schema.Random.Builder();
    } else {
      return new io.axual.client.example.schema.Random.Builder(other);
    }
  }

  /**
   * RecordBuilder for Random instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Random>
    implements org.apache.avro.data.RecordBuilder<Random> {

    /** The random value. */
    private java.lang.CharSequence random;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.axual.client.example.schema.Random.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.random)) {
        this.random = data().deepCopy(fields()[0].schema(), other.random);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Random instance
     * @param other The existing instance to copy.
     */
    private Builder(io.axual.client.example.schema.Random other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.random)) {
        this.random = data().deepCopy(fields()[0].schema(), other.random);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'random' field.
      * The random value.
      * @return The value.
      */
    public java.lang.CharSequence getRandom() {
      return random;
    }


    /**
      * Sets the value of the 'random' field.
      * The random value.
      * @param value The value of 'random'.
      * @return This builder.
      */
    public io.axual.client.example.schema.Random.Builder setRandom(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.random = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'random' field has been set.
      * The random value.
      * @return True if the 'random' field has been set, false otherwise.
      */
    public boolean hasRandom() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'random' field.
      * The random value.
      * @return This builder.
      */
    public io.axual.client.example.schema.Random.Builder clearRandom() {
      random = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Random build() {
      try {
        Random record = new Random();
        record.random = fieldSetFlags()[0] ? this.random : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Random>
    WRITER$ = (org.apache.avro.io.DatumWriter<Random>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Random>
    READER$ = (org.apache.avro.io.DatumReader<Random>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.random);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.random = in.readString(this.random instanceof Utf8 ? (Utf8)this.random : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.random = in.readString(this.random instanceof Utf8 ? (Utf8)this.random : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










